name: Build Vitamin LineageOS

on:
  workflow_dispatch:
    inputs:
      device_tree:
        description: "Device tree link"
        required: true
        default: ""
      rom_repo:
        description: "ROM repository link (with manifest)"
        required: true
        default: ""
      device_codename:
        description: "Device codename (e.g., 'vitamin')"
        required: true
        default: "vitamin"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install prerequisites
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev \
                                  gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
                                  libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig \
                                  repo python3 python3-pip cmake
          echo "Installed basic prerequisites"

      # Step 2: Install ccache from source
      - name: Install ccache from source
        run: |
          cd /tmp
          wget https://github.com/ccache/ccache/releases/download/v4.8.2/ccache-4.8.2.tar.gz
          tar -xvf ccache-4.8.2.tar.gz
          cd ccache-4.8.2
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install
          echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc
          ccache --version

      # Step 3: Update repo tool to latest version
      - name: Update repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
          chmod a+x /usr/local/bin/repo
          repo --version  # Check the version to ensure it's updated

      # Step 4: Clone the LineageOS manifest (without vitamin lineage)
      - name: Initialize LineageOS repository
        run: |
          mkdir -p $HOME/lineageos
          cd $HOME/lineageos
          git clone "${{ github.event.inputs.rom_repo }}" rom-source  # Clone the manifest repository
          cd rom-source
          repo init -u . -b lineage-21.0  # Sync the correct branch: lineage-21.0
          repo sync --force-sync --no-clone-bundle --current-branch --jobs=$(nproc)  # Sync the repositories
        shell: bash

      # Step 5: Clone the device tree
      - name: Clone device tree
        run: |
          cd $HOME/lineageos/rom-source
          git clone "${{ github.event.inputs.device_tree }}" device-tree
        shell: bash

      # Step 6: Build the ROM with mka bacon
      - name: Build Vitamin LineageOS with mka bacon
        run: |
          cd $HOME/lineageos/rom-source
          source build/envsetup.sh
          lunch vitamin_${{ github.event.inputs.device_codename }}-lineage-ap2a-user
          mka bacon -j$(nproc)  # Using all available CPU cores for parallelization
        shell: bash

      # Step 7: Upload the build artifacts
      - name: Upload ROM
        uses: actions/upload-artifact@v3
        with:
          name: vitamin-lineageos-build
          path: $HOME/lineageos/rom-source/out/target/product/*
