name: Download and Upload to Release

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: "URL of the file to download"
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the file from the provided URL
      - name: Download File
        run: |
          echo "Downloading file from: ${{ inputs.file_url }}"
          curl -L -o downloaded_file "${{ inputs.file_url }}"

      # Step 2: Compress the file (optional)
      - name: Compress Downloaded File
        run: |
          echo "Compressing the downloaded file..."
          zip -r downloaded_file.zip downloaded_file

      # Step 3: Upload to GitHub Release
      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name || 'manual-release' }}
          name: Release ${{ github.ref_name || 'Manual Release' }}
          artifacts: downloaded_file.zip
          artifactContentType: application/zip
