name: Download from PixelDrain and Upload to Release

on:
  workflow_dispatch:
    inputs:
      pixeldrain_url:
        description: "PixelDrain URL of the file to download"
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the file from PixelDrain
      - name: Download file from PixelDrain
        run: |
          echo "Downloading file from: ${{ inputs.pixeldrain_url }}"
          curl -L -o downloaded_file "${{ inputs.pixeldrain_url }}"

      # Step 2: Compress the file (optional)
      - name: Compress Downloaded File
        run: |
          echo "Compressing the downloaded file..."
          zip -r downloaded_file.zip downloaded_file

      # Step 3: Create a Release and Upload the File
      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name || 'manual-release' }}
          name: Release ${{ github.ref_name || 'Manual Release' }}
          artifacts: downloaded_file.zip
          artifactContentType: application/zip
