name: Download Torrent and Upload to Release

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: "URL of the torrent file to download"
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install aria2 (a lightweight torrent downloader)
      - name: Install aria2
        run: sudo apt-get install -y aria2

      # Step 2: Download the torrent file
      - name: Download Torrent File
        run: |
          echo "Downloading torrent file from: ${{ inputs.torrent_url }}"
          curl -L -o file.torrent "${{ inputs.torrent_url }}"

      # Step 3: Download the files using the torrent
      - name: Download Files from Torrent
        run: |
          echo "Downloading files from torrent..."
          aria2c --seed-time=0 --summary-interval=1 -T file.torrent -d downloaded_files

      # Step 4: Compress the downloaded files (optional)
      - name: Compress Downloaded Files
        run: |
          echo "Compressing downloaded files..."
          zip -r downloaded_files.zip downloaded_files

      # Step 5: Create a Release and Upload the Files
      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name || 'manual-release' }}
          name: Release ${{ github.ref_name || 'Manual Release' }}
          artifacts: downloaded_files.zip
          artifactContentType: application/zip
